### ISSUE TITLE
ui: refreshing page inside a bucket causes 404

### ISSUE THREAD

**Issue by artur9010** [SiaFoundation/renterd#1026]
### Current Behavior

![image](https://github.com/SiaFoundation/renterd/assets/4835677/a493d379-9055-4aaa-82de-7287d5a18600)

### Expected Behavior

Load file list

### Steps to Reproduce

1. Go to bucket list
2. Go into any bucket
3. Try to refresh page (F5)

### Version

de431b6

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu, Kubernetes (https://github.com/artur9010/charts/tree/master/renterd)

### Autopilot Config

x

### Bus Config

x

### Contract Set Contracts

x

**Comment by alexfreska** [comment]
This issue is caused by the new route pattern for buckets and files:

/buckets/**bucket_name**/files/**path/to/directory**

which generates an html entry point like:
```
/buckets/[bucket]/files/[[...path]].html
```
The special `nextjsRouter` static `http.Handler` does not support the param + catch all combo: https://github.com/SiaFoundation/web/blob/main/ui/ui.go

It needs to work for this sort of case: https://github.com/SiaFoundation/web/commit/c8795ebf96b24bb7fe2e8011947982aa4bf43833#diff-797a8ca0587dda82ce75e0a8c8a5b08207d68ca17ee1dfbe1b4d33e6ba0af258R205-R206

@n8maninger is this is a difficult change? I am not familiar with that magical code 😅
