### ISSUE TITLE
Improve the reclaimable space stat

### ISSUE THREAD

**Issue by alexfreska** [SiaFoundation/renterd#1247]
Instead of reclaimable space, move to more accurate prunable and expiring space stats.

**Comment by alexfreska** [comment]
@peterjan what did we decide for this? I had the change drafted, but we needed to find a way around that slow (8 min) endpoint response.

**Comment by peterjan** [comment]
Chris and I talked about it briefly, nothing was ultimately decided though I don't think. I think for now we should probably make use of the fact that we called it "reclaimable space" and haven't really set in stone that matches the data that's being pruned should you enable the feature...

I think it's safest to extend the `/stats/objects` endpoint with a new value called `totalExpiringSize` (`totalUploadedSize`-`totalSectorsSize`) and rename reclaimable space to expiring space. We could combine this with an extra column perhaps in the contracts table called "prunable data" and fetch the prunable data for every contract using `/contract/:id/size` but I wouldn't do that for the time being.

I tried thinking of a cheap guesstimate but I haven't been able to come up with one that's remotely close to the _actual_ data we select for pruning. If you want to have cheap guesstimates you have to probably try to use number of slabs, number of shards and perhaps contract sizes but I don't see how you combine those to get at the value you'd get from actually joining on the contract sectors.

cc @ChrisSchinnerl  what do you think? Kind of lame but on the other hand not too bad? Reclaimable space now equals `totalUploadedSize`-`totalSectorsSize` which we definitely have to change because that's not correct. I think we can't easily get a number that goes to 0 if you enable pruning so by renaming it to expiring data you show the user how much data he'll stop paying for on renew and we're not setting ourselves up for failure because we're not mentioning pruning and we're not giving a number that should go down to 0.

**Comment by ChrisSchinnerl** [comment]
I don't think we need to extend anything for that right now? If we rename `reclaimable space` to `expiring data` and compute that value on the client side by just adding up the `size` of all contracts not in the contract set we should be good. 

Long term I'd split `/stats/objects` up into
- `/stats/objects` -> `MinHealth`, `NumObjects`, `NumUnfinishedObjects`, `TotalObjectsSize` (filters: `bucket`)
- `/stats/slabs` -> `TotalSlabsSize`, `TotalSectorsSize` (filters: `contractSet`)
- `/stats/contracts` -> `TotalUploadedSize` (filters: `contractSet`)

Then giving an estimate would be quite simple by comparing `TotalUploadedSize` for the `autopilot` contract set with `TotalSectorsSize` for the `autopilot` set. 
Splitting routes up is also nice since we don't need to perform the full heavy operation every time and can refresh certain parts of the stats in different intervals or even on demand.

**Comment by alexfreska** [comment]
@ChrisSchinnerl  @peterjan  here is a visual comparison of values on gompa. The first two prunable and expiring are calculated using the prunable endpoint (which can be slow), I added the second expiring which is the total size across all contracts that are not in the autopilot set. Do the numbers look good?

Just to confirm, is the idea now to only show that 3rd value, and name it "expiring data"?

![Image](https://github.com/SiaFoundation/renterd/assets/1412796/86499a39-e3bc-40e9-a6ce-c559f514b83c)

**Comment by alexfreska** [comment]
Today we decide to take this in a new direction:

The prunable API response time has been improved so we will stick to using it. But because it is resource intensive to run, we will make it on-demand instead of the current behaviour which is to be automatically triggered by all clients every 10 min (cache time).

The prunable data stats will also be moved to the contracts page where it can be requested and displayed via a button on the navbar. The data will also be displayed in the table per contract, the user can also request the information for just an individual inline.
