### ISSUE TITLE
`renterd config` enables S3 when not asked

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#1612]
### Current Behavior

The setup wizard of `renterd config` asks whether I want to configure the S3 settings. If I say "no", it still generates a `renterd.yml` file where `s3: enabled` equals to `true`.

### Expected Behavior

If I tell `renterd config` that I do not want to configure the S3 settings, I imply that I do not want to enable S3. Therefore, it needs to be disabled in the config file.

### Steps to Reproduce

1. Run `renterd config`.
2. Say "no" to "would you like to configure S3 settings".

### Version

v1.1.0-beta.5

### What operating system did the problem occur on (e.g. Ubuntu 22.04, macOS 12.0, Windows 11)?

Ubuntu 24.04

### Autopilot Config

N/A

### Bus Config

N/A

### Contract Set Contracts

N/A

**Comment by ChrisSchinnerl** [comment]
Right now saying "no" to "Would you like to configure X" doesn't mean that X gets disabled but rather that you don't configure it and accept the defaults. Which for S3 is "enabled".

We can follow up with another prompt "Would you like to enable the S3 gateway" though which can then be used to enable/disable S3 explicitly. The default is "enabled" because there is no harm in doing so. Without creating any keys, nothing can access the gateway.
