### ISSUE TITLE
Host rescan not showing most recent prices

### ISSUE THREAD

**Issue by mike76-dev** [SiaFoundation/renterd#323]
One host has been stuck on the gouging list since 3 weeks ago (according to the host). Here is the `renterd` screenshot:
![image](https://user-images.githubusercontent.com/72828450/235303580-dc5bffaf-a07a-479d-9c65-0f849a500a3b.png)
However, this host has quite different prices according to Sia Central:
![image](https://user-images.githubusercontent.com/72828450/235303631-7ce8b173-bd6d-4cde-8135-3b7f26ebf85b.png)
A manual host rescan in `renterd` doesn't change the result.

**Comment by peterjan** [comment]
Thanks Mike! I think I know why this is happening, I will fix this soon. It's because the manual rescans don't pay for the price table updates. If the price table is not paid for, we don't persist it in the host database because we use it as a price table cache for the worker. Fix is relatively straightforward though I'll start on it today or tomorrow.

**Comment by peterjan** [comment]
@mike76-dev turns out the change I wanted to make is actually already how the price tables are being updated, I think everyone might be working as expected and this host is in fact considered price gouging. Sia Central might calculate things differently, for instance, we include the redundancy in the pricing, and we also include the storage costs in the upload price. Keeping those things in mind I think the gouging errors make sense. We would have to compare the `renterd` price table with the price table Sia Central is using but I'm not sure they expose it. I think we can treat this as a non-issue though if this is the only host that is behaving this way.

I do agree it's kind of annoying there's this mismatch between how you can interpret a host if you look it up through Sia Central versus if you see a host in the renterd UI but due to the way we decided we'd put gouging checks in-place, I don't think we can easily move towards a UI or gouging checks that would correspond 1-1 with Sia Central.

**Comment by mike76-dev** [comment]
Thanks, that would make sense. I will ask the host to change the price and then check if it has an effect. Will do that in a couple of days as I’m traveling now.

**Comment by mike76-dev** [comment]
I did what I was going to do. Indeed, the host's price changes are reflected in `renterd` when a manual rescan is forced.
I'm closing the issue now.
