### ISSUE TITLE
Add an alert or endpoint for identifying lost files

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SiaFoundation/renterd#694]
An object that can't be retrieved anymore should cause an alert to be registered that allows a user to take measures to recover the file.

**Comment by peterjan** [comment]
#717 introduced new alerts that notify the user when critical migrations succeed and/or fail, it will also hint at using the new gouging setting called `MigrationSurchargeMultiplier` that allows overpaying hosts to try and recover a potentially otherwise lost file. I think in combination with [an endpoint that allows fetching objects by their health](https://github.com/SiaFoundation/renterd/issues/707) (and thus making it easier to identify potentially lost files), we can close out this issue?
