### ISSUE TITLE
Multipart (large file) upload in UI

### ISSUE THREAD

**Issue by pcfreak30** [SiaFoundation/renterd#975]
### Description

Based on a community discord chat https://discord.com/channels/809849352516141067/946328563320238190/1208222287392804904, the UI uploader needs to switch to the multipart upload endpoints for files over X filesize, and ideally store this meta to local browser storage so it can be picked back up later or in case of failures.

**Comment by ChrisSchinnerl** [comment]
While we are planning on integrating multipart uploads already as part of a new view for multipart uploads, the issue you have linked to will likely not resolve itself by using multipart uploads. 
The problem seems to be that the contract set contains 18 contracts and the file is uploaded to 16 hosts, causing the upload to fail if 3+ hosts disappear.
